apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
  namespace: ecommerce
type: Opaque
data:
  STRIPE_SECRET_KEY: c2tfdGVzdF9leGFtcGxlX2tleQ==
  STRIPE_WEBHOOK_SECRET: d2hfc2VjcmV0X2tleQ==
