apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-service
  namespace: ecommerce
spec:
  hosts:
  - product-service
  http:
  - match:
    - uri:
        prefix: /api/products
    route:
    - destination:
        host: product-service
        port:
          number: 8082
        subset: v1
      weight: 100
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /api/categories
    route:
    - destination:
        host: product-service
        port:
          number: 8082
        subset: v1
      weight: 100
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 5s
